Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
  
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nginx git
  
      # Klone das Git-Repository
      git clone https://github.com/Marco-Mueller1/Git-Tests.git /vagrant/repo
  
      # Konfiguriere Nginx, um auf die HTML-Datei im Repository zu verweisen
      sudo rm /var/www/html/index.nginx-debian.html
      sudo ln -s /vagrant/repo/index.html /var/www/html/
  
      sudo service nginx restart
    SHELL
  end